### ISSUE TITLE
Release filename is only the version ; suggest reponame-version

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#10]
@0pcom commented on Sep 9

This issue affects every skycoin repo except skyflash

If one should want to download the release source .tar.gz of every skycoin repo, the filename is ONLY the package version. Example:

https://github.com/skycoin/skycoin/archive/v0.26.0.tar.gz

This may not be a critical issue, but it is generally a headache that the releases are only titled with their versions; and certain to cause conflicts (for build automation) if two repo releases have the same version at the same time.

Skywire and hardware-wallet-daemon are .1 away from being the same version on their most recent release.

I suggest that the release .tar.gz be titled as reponame-version

i.e. skycoin-0.26.0

**Comment by iketheadore** [comment]
The release filename is generated by github when we add a tag. The filename would be `reponame-version` if we open the link from browser. If we download it through command line tool like `wget`, it will be `version` only.  But we can use `wget -O` to rename it.
