### ISSUE TITLE
CLI create_rawtx txn verification should request /blockchain/metadata

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#119]
@gz-c commented on Jan 30, 2018

Depends on [#914](https://github.com/skycoin/skycoin/pull/914) and [#915](https://github.com/skycoin/skycoin/issues/915)

See "TODO" marked in api/cli/create_rawtx.go for details, after [#914](https://github.com/skycoin/skycoin/pull/914) merges

**Comment by iketheadore** [comment]
The endpoint of `/outputs` returns the head block data which is the same as `/blockchain/metadata`. Hence, no need to call it again.
