### ISSUE TITLE
Document offline transaction signing

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#135]
@gz-c commented on Nov 22, 2017

The CLI can use a local wallet file to sign transactions. It still needs to request to a skycoin node for unspent outputs, but the hot wallet can be kept separate from the node.

Document "Offline Transaction Signing" with instructions on how to use the skycoin cli to do this, and also point to the godoc docs for the code API to add this functionality to a go application.

**Comment by vidya88** [comment]
@gz-c commented on Apr 17, 2018

Some related instructions are in INTEGRATION.md and src/api/cli/README.md

The main README.md should have a section "Offline Transaction Signing" that describes how to use the cli tool to sign transactions with a local wallet. The user could also run the node with networking disabled, such that they'd only need a recent-enough copy of the blockchain database to create their transaction (although they'd lose out on some coin hours, depending on how old the blockchain database copy was).

**Comment by iketheadore** [comment]
The `skycoin-cli` does not have command to do offline transaction signing yet.

**Comment by iketheadore** [comment]
Fixed in #166
