### ISSUE TITLE
Request: Add address book

### ISSUE THREAD

**Issue by 4rchim3d3s** [SkycoinProject/skycoin#174]
Add an address book to easy transact Sky to known users.
-> to use in Skycoin-Apps (android, apple, windows, web ...)

userflow for example:

1. Press on button "Add Address" 
2. Put in pubkey address
3. Put in alias name
4. select option where to save address: 
    * attached to my pubkey address (so maybe store the address book on a cx-chains "database")
    * local on this device

Then when sending to someone the user just has to fill in amount and description.

**Comment by iketheadore** [comment]
It would be convenient for senders, but it actually has some security problems:
1. How could the sender verify the address that bond to the user is correct. 
2. No receiver would like to expose their address and username to a public database.
