### ISSUE TITLE
Request: Add periodic transactions

### ISSUE THREAD

**Issue by 4rchim3d3s** [SkycoinProject/skycoin#175]
Add a feature to automate payments / transactions on a periodic base or 
to make a transaction on a set timestamp

For example:

 ### Periodically

Send x amount to address y every z (hours,days,minutes,weeks,months,years)
or
Send x amount to address y on every z th of the month

option for both examples:

start from *date* end (never, on date, after n transactions)

### one timed transaction

Send x amount to address y on *date* and *time*

**Comment by iketheadore** [comment]
User could write a script to do this kind of work by call the APIs or `skycoin-cli`.
