### ISSUE TITLE
Create an API endpoint for generating offline transactions

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skycoin#203]
To be able to include in the desktop wallet a form for creating offline transactions and solve #124 an API endpoint for creating transactions without having a synchronized blockchain is needed. At this moment it is possible to create transactions with some freedom with the `/api/v2/transaction` API endpoint, but the problem is that it just receives the hashes of the inputs, the node automatically recovers the coins and hours balance of each input from the blockchain and then makes all the calculations, which does not work in the case of an offline node.

What is needed is to create a new API endpoint similar to `/api/v2/transaction` (or to modify it) so a transaction can be created by sending to the backend the full information about the inputs (hash, coins and hours).

**Comment by iketheadore** [comment]
A synchronized or nearly synchronized blockchain is needed, no matter online or offline. We need it to retrieve data to construct and verify transactions. The 'offline` just mean without networking connection, not without synchronized blockchain. 

What we need to do in UI are:
- Create unsigned transactions in GUI (not offline yet), users should have the same experience as when trying to send coins, the difference is the returned result is an unsigned transaction.
- Sign the transaction with an offline wallet in GUI.

**Comment by Senyoret1** [comment]
The problem with that approach is we would need "watch only" wallets implemented first. Here is the situation: for being able to create the unsigned transaction using an online desktop wallet, the user would have to enter the seed on that desktop wallet first, in a computer connected to the internet, so that wallet is already able to sign the transaction and send it to the network, there is not point in signing it in an offline wallet. Also, that wallet would be already exposed to the risk of sending the seed to an attacker.

The point of #124 is to let users install the desktop wallet in a computer that will never be connected to the internet, create a wallet using it and never putting the seed in another electronical device, so no malware is able to steal the seed. The thing is that following those rules means that the offline desktop wallet will be the only one able to create and sign transactions. At this moment no other software wallet will be able to create transactions with that wallet, even unsigned transactions, because it would be requered to enter the seed just for showing the wallet on the UI and allow the user to create the transaction (even if it won't be signed), which the user will not do. That is why the desktop wallet would need a special form allowing the user to enter the inputs manually, including the hash, the coins and the hours, to be usable in the offline wallet. Now, here are the options:

- As requested in this issue, we could create a new API endpoint similar to `/api/v2/transaction`, but changing the fact that it would need to receive a detailed list of the inputs, including hash, coins and hours, so that the node does not need to check the blockchain for getting the input data. This obviously neans that the user will be able to lie in any of those data fields and that would end in the node creating an invalid transaction, but it should not matter as transactions will be checked in the online wallet before sending them. It should also be taken into account that the user could enter more or less inputs than necessary. For making the wallet UI less tedious for the user, we can add an option to the explorer for creating a test string which cold be used for populating the form with all the available inputs, just by pasting it.

- We could avoid creating the new endpoint and I can just adapt and fix an old code from the web wallet to create the transaction directly from TypeScript. The disadvantages with this approach are that the code could be a bit different from the one used in the node (that would mainly mean some differences in coin hours distribution and inhability to automatically take advantage of inprovements made in the node) and that there is a small posibility of needing to use skycoin-lite (parts of the Skycoin node code compiled to wasm) for calculating the inner hash of the transactions (I would first need to investigate if I can do it reliably with TypeScript). At lest the transaction encoder is already ported to JavaScript.

- We could also make the desktop wallet able to add "watch only" wallets and use the approch you described, but that would need additional changes to be made first.

**Comment by Senyoret1** [comment]
The problem with that approach is we would need "watch only" wallets implemented first. Here is the situation: for being able to create the unsigned transaction using an online desktop wallet, the user would have to enter the seed on that desktop wallet first, in a computer connected to the internet, so that wallet is already able to sign the transaction and send it to the network, there is not point in signing it in an offline wallet. Also, that wallet would be already exposed to the risk of sending the seed to an attacker.

The point of #124 is to let users install the desktop wallet in a computer that will never be connected to the internet, create a wallet using it and never putting the seed in another electronical device, so no malware is able to steal the seed. The thing is that following those rules means that the offline desktop wallet will be the only one able to create and sign transactions. At this moment no other software wallet will be able to create transactions with that wallet, even unsigned transactions, because it would be requered to enter the seed just for showing the wallet on the UI and allow the user to create the transaction (even if it won't be signed), which the user will not do. That is why the desktop wallet would need a special form allowing the user to enter the inputs manually, including the hash, the coins and the hours, to be usable in the offline wallet. Now, here are the options:

- As requested in this issue, we could create a new API endpoint similar to `/api/v2/transaction`, but changing the fact that it would need to receive a detailed list of the inputs, including hash, coins and hours, so that the node does not need to check the blockchain for getting the input data. This obviously neans that the user will be able to lie in any of those data fields and that would end in the node creating an invalid transaction, but it should not matter as transactions will be checked in the online wallet before sending them. It should also be taken into account that the user could enter more or less inputs than necessary. For making the wallet UI less tedious for the user, we can add an option to the explorer for creating a test string which cold be used for populating the form with all the available inputs, just by pasting it.

- We could avoid creating the new endpoint and I can just adapt and fix an old code from the web wallet to create the transaction directly from TypeScript. The disadvantages with this approach are that the code could be a bit different from the one used in the node (that would mainly mean some differences in coin hours distribution and inhability to automatically take advantage of inprovements made in the node) and that there is a small posibility of needing to use skycoin-lite (parts of the Skycoin node code compiled to wasm) for calculating the inner hash of the transactions (I would first need to investigate if I can do it reliably with TypeScript). At lest the transaction encoder is already ported to JavaScript.

- We could also make the desktop wallet able to add "watch only" wallets and use the approch you described, but that would need additional changes to be made first.

**Comment by Senyoret1** [comment]
Another option would be adding 3 new functionalities: a form that allows the user to create an unsigned transaction from an online wallet by manually entering the addresses and outputs to use, an option for signing a transaction (it would not need the wallet to be online) and an option for broadcasting an transaction. This would allow the user to create the transaction with an online wallet, sign it with the offline wallet and send it using the online wallet again.

**Comment by Senyoret1** [comment]
The problem with that approach is we would need "watch only" wallets implemented first. Here is the situation: for being able to create the unsigned transaction using an online desktop wallet, the user would have to enter the seed on that desktop wallet first, in a computer connected to the internet, so that wallet is already able to sign the transaction and send it to the network, there is not point in signing it in an offline wallet. Also, that wallet would be already exposed to the risk of sending the seed to an attacker. The point of #124 is to let users install the desktop wallet in a computer that will never be connected to the internet, create a wallet using it and never putting the seed in another electronical device, so no malware is able to steal the seed.

I think the closer solution would be to add 3 new functionalities: a form that allows the user to create an unsigned transaction from an online wallet by manually entering the addresses and outputs to use, an option for signing a transaction (it would not need the wallet to be online) and an option for broadcasting an transaction. This would allow the user to create the transaction with an online wallet, sign it with the offline wallet and send it using the online wallet again.

**Comment by Senyoret1** [comment]
Sorry for changing the comment several times, I was checking the available options

**Comment by iketheadore** [comment]
Yes, that would require the `watch only` wallet. Before that, we need the form as you proposed to create the unsigned transaction with an online wallet, and have the option to sign it with an offline wallet, also need an option to broadcast the signed transaction with an online wallet.

We may need to have the option that let user select outputs from the addresses they entered. We also need to warn users that the enter the addresses should from the same wallet, as we can not sign transaction that have the inputs from different wallets yet.

**Comment by Senyoret1** [comment]
Closed as offline transactions were already added to https://github.com/SkycoinProject/skycoin/pull/186 , as discussed
