### ISSUE TITLE
Do not show all transactions in the history immediately

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#24]
@Senyoret1 commented on Jun 8

If the user has a lot of transactions, the history shows a very long list and that affects the performance. In fact, the application freezes for a few seconds if the list is too large. To avoid this, the history needs pagination or a "load more" button.

**Comment by vidya88** [comment]
@gz-c commented on Jun 8

Depends on #2090

**Comment by vidya88** [comment]
@Senyoret1 commented on Jun 9

It could start to be implemented before #2090 with a similar approach to the one used in the explorer. The main problem is adding too many elements to the UI at the same time, so for the moment all the elements could be kept in memory and simply avoid adding all to the UI at the same time. It would not be a perfect solution, it would be better with #2090, but it would improve the performance a lot when the number of transactions is excessive.

**Comment by iketheadore** [comment]
Fixed, could have further optimization by calling `/api/v2/transactions` with pagination.
