### ISSUE TITLE
BTC Integration Desktop side

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/skycoin#245]
**Development tasks**

- [ ] implement BTC wallet functionality 

The Skycoin wallet can be used as reference for the functionality we need.

- [ ] copy over RPCClient for btcd

Optimally we would strip out functionality that is not required. If uncertain, we should leave code untouched as overly zealous code deletion lead to issues in Skywallet before.

- [ ] integrate dmsg-http client with the desktop wallet

This is not priority and should be tackled only if the other tasks have been finished. 

**Deployment tasks**

- [ ] deploy btcd node inside docker container with automatic restarting and monitoring

- [ ] setup dmsg-http server on the deployment

**Comment by iketheadore** [comment]
Will the BTC wallet function integrated into skycoin wallet directly?  I'm not sure if this is necessary, I see PR #247 added 74,506 lines of code, most of them are vendor files of btcd. This would make our wallet too fat.  I  think skycoin wallet should only support skycoin, just like BTC wallet won't integration ETC or LTC and vice versa. If we want to provide a wallet that support multiple coins, then we might need to do it in a separate project, which has a light backend that calls APIs to communicate with nodes(skycoin, btc, eth,  etc), and frontend code for the Wallet UI.
