### ISSUE TITLE
Transaction violates soft constraint: Transaction coinhour fee minimum not met 

### ISSUE THREAD

**Issue by lfj7282** [SkycoinProject/skycoin#252]
when i do this /api/v1/injectTransaction get error
[2020-03-26T10:26:25+08:00] ERROR [daemon]: InjectUserTransactionTx failed error="Transaction violates soft constraint: Transaction coinhour fee minimum not met"
[2020-03-26T10:26:25+08:00] ERROR [api]: 400 POST /api/v1/injectTransaction 45.911631ms body="400 Bad Request - Transaction violates soft constraint: Transaction coinhour fee minimum not met"

this is my transaction detail
{
"hexIn":[
"0a8498ee44ce568da56631e64b6e87614282c463abaa19effb3b583d8983977e"
],
"hexInnerHash":"a8f81ad08efe8dc6c7e4e764f3c389e2c6456c1d76784392f38d9ed21454d857",
"inputAddress":[
"2C2YnkpGqTCzLMHS6mTnUuwx8xqj1XGeE8"
],
"length":0,
"out":[
{
"base58Addr":"ArgqfWrdnVroFbvpreoGicrFHQVqFu84ddtSSWKZ",
"coins":25976000,
"coinsStr":"25.976000",
"hours":1,
"hoursStr":"1"
},
{
"base58Addr":"8ngopZYFGb2Dazt6nQ9nZp2Dw2pdEMxY4KmUryg",
"coins":2249288000,
"coinsStr":"2249.288000",
"hours":12055304,
"hoursStr":"12055304"
}
],
"type":0
}

can someone help me,how to fix it.

**Comment by iketheadore** [comment]
Hi, what's wallet version are you using.

**Comment by lfj7282** [comment]
> Hi, what's the wallet version are you using.

0.26.0

**Comment by iketheadore** [comment]
v0.26.0 should already reduced the coin hour fee to 10%. Base on the transaction info you provided above, the coin hour fee should be enough. Can you post the raw transaction hex string so that I can test and see what's the problem. Thank you.

**Comment by lfj7282** [comment]
> v0.26.0 should already reduced the coin hour fee to 10%. Base on the transaction info you provided above, the coin hour fee should be enough. Can you post the raw transaction hex string so that I can test and see what's the problem. Thank you.

dc00000000a8f81ad08efe8dc6c7e4e764f3c389e2c6456c1d76784392f38d9ed21454d85701000000f039e8bf7617d80725c2d08f23b31f3231fb957fed7459c4f81de0121ed393f0428d26ddcb2905ed052234e02fbdcbfffc92a019fec52cdfbb7aa453c976703800010000000a8498ee44ce568da56631e64b6e87614282c463abaa19effb3b583d8983977e0200000000d91f1e99936456b85d287a40c18e2ca269b073f5c05c8c010000000001000000000000000002f52ba18db8fc126d942cecf73bef6f465cbd98406911860000000008f3b70000000000

**Comment by iketheadore** [comment]
Sorry for the late response. I tested the transaction locally and it is spendable. Can you run the api `http://127.0.0.1:6420/api/v1/health` and check the `burn_factor` value. It should be `10`, if you get the value of `2`. Then you might need  to update the wallet  to latest version.

**Comment by lfj7282** [comment]
> Sorry for the late response. I tested the transaction locally and it is spendable. Can you run the api `http://127.0.0.1:6420/api/v1/health` and check the `burn_factor` value. It should be `10`, if you get the value of `2`. Then you might need to update the wallet to latest version.

it is amazing!
first, i sure my wallet version is 0.26.0. and i reject this raw transaction return error at last two days.
second, just now, i try to do this 'curl -x POST http://127.0.0.1:6420/api/v1/health' ,it return 405 Method Not Allowed.
then i rejectTransaction again ,it is success. 
but this raw transaction is build two days ago. so i think my cion hours  is less than which build transaction in currency time. but  it is not a big deal.
finally. thanks  anyway.

**Comment by iketheadore** [comment]
That's good,  cheers!

I will close this issue, if you get any further questions, feel free to create a new issue for it.
