### ISSUE TITLE
Possible DB corruption bug

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#26]
@gz-c commented on Jun 3

User's wallet failed to start due to this error:

```
DB verify checkpoint version: 0.25.0
[2019-06-03T00:24:15+02:00] INFO [main]: Checking database and resetting if corrupted
[2019-06-03T00:24:15+02:00] ERROR [visor]: bc.store.ForEachBlock failed: Not enough buffer data to deserialize
[2019-06-03T00:24:15+02:00] ERROR [main]: visor.ResetCorruptDB failed: Not enough buffer data to deserialize
[2019-06-03T00:24:15+02:00] INFO [main]: Closing database
[2019-06-03T00:24:15+02:00] INFO [main]: Goodbye
```
However, they did not send me the db file before he deleted it

**Comment by BigOokie** [comment]
Have taken a quick look at this one. I can see the call stack appears to be as follows:
- Coin.Run()
- visor.RestCorruptedDb()
- CheckDatabase()
- blockchain.WalkChain()
The initial error is reported in here - `bc.store.ForEachBlock failed` and comes from the `default` clause in the switch statement which is evaluating `err.(type)`. The only error type that is checked for explicitly here is `blockdb.ErrMissingSignature`.
I need to dig further, but possibly (need to confirm this) the `nil` is then returned from this function.

If that is the case, then `ResetCorruptedDB` will receive `nil` as the result when it has called `CheckDatabase`. `ResetCorruptedDB` then evaluates `err.(type)` and if it is `nil` then the `db` and `nil` are both returned - meaning that database corruption was not identified.

The only cases where DB corruption is flagged by `ResetCorruptDB` is when `err.(type)` evaluates to either `blockdb.ErrMissingSignature` or `historydb.ErrHistoryDBCorrupted`.  If either of these cases occur then the private function `resetCorruptDB()` is called.

Based on the information in the errors that has been logged, its clear that something is being missed here, and this scenario should result in the database being reset (IMO).

**Comment by BigOokie** [comment]
Further digging shows the actual root error is coming from the attempt to decode the blocks when walking the blockchain (`blockchain.WalkChain()`), and from a call to these functions specifically:
- `block_skyencoder.decodeBlockExact`
- `block_skyencoder.decodeBlock`

The `block_skyencoder.decodeBlock` function can throw an error of type `encoder.ErrBufferUnderflow` at multiple points - and is what is being reported in the log file in this instance. This error constant is defined in `encoder.go`:
```
// ErrBufferUnderflow bytes in input buffer not enough to deserialize expected type ErrBufferUnderflow = errors.New("Not enough buffer data to deserialize")
```
I note that the `decodeBlock()` function can throw the following errors:
- `encoder.ErrBufferUnderflow`
- `encoder.ErrMaxLenExceeded`

So I propose (to be discussed) that the these two specific error types should be added to error type evaluation in the `ResetCorruptDB()` function - and if either of these have occurred then the database should be deemed to be corrupted and a call made to the `resetCorruptDB()` function be made to resolve it (by creating a new instance of the Db).

I will raise PR to examine this option and open it for further discussion and review.

**Comment by BigOokie** [comment]
Except... these are not types they are constants:
- `encoder.ErrBufferUnderflow`
- `encoder.ErrMaxLenExceeded`

More thought needed. But I think this is heading in the right direction.
