### ISSUE TITLE
Create a guide and docker container for running a public API node

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#27]
@gz-c commented on Jun 2

_No description provided._

**Comment by vidya88** [comment]
@gz-c commented on Jul 10

Related to or duplicate of [#2361](https://github.com/skycoin/skycoin/issues/2361)

**Comment by BigOokie** [comment]
You will want to take into consideration #31 to ensure the node can be run using HTTPS

**Comment by iketheadore** [comment]
Duplicate of #31
