### ISSUE TITLE
Change the colors of DoubleButtonComponent

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#32]
@Senyoret1 commented on May 24

When `DoubleButtonComponent `is white, the colors are so subtle that it is very difficult to see which button is selected. It is very likely that the problem is more or less notorious depending on the monitor used.

**Comment by Senyoret1** [comment]
@iketheadore . Fixed in https://github.com/SkycoinProject/skycoin/issues/195 . Please close this issue as I do not have permissions to do it.
