### ISSUE TITLE
Check that wallet can be created when offline

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#42]
@gz-c commented on Apr 7

Possible report of failure to create the first wallet when the software is run with no internet connection. This would be a bug.

1. With a clean data-directory, run the electron wallet offline. Verify you can create a wallet
2. With a data-directory that already has a wallet, run the electron wallet offline. Verify you can create a wallet

If either of these fails, create a new issue with steps to reproduce and label it as a bug.

**Comment by iketheadore** [comment]
Wallet can be created when offline
