### ISSUE TITLE
Logging error responses from v2 APIs should exclude "data"

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#57]
@gz-c commented on Feb 20

When an API responds with an error, the response is logged.

For /v1 endpoints the response will be like "400 Bad Request - foo" but for /v2 endpoints the response will be a JSON object and may include a "data" section even if there is an error (e.g. /api/v2/transaction/verify).

For /v2 endpoints, log the "error"["message"] value instead of the entire response.
It should avoid re-parsing the JSON response just to get this message; restructuring is necessary to log this error message without reparsing.

**Comment by iketheadore** [comment]
The "data" has already been excluded, however, to only print the error message, re-parsing is now the easiest and relatively elegant way for it. Another way is put the error message in the response header, but that would add extra data to response header, which is not the style of our  APIs.
