### ISSUE TITLE
Include SrcTransaction in verbose transaction inputs

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#59]
@gz-c commented on Feb 15

_No description provided._

**Comment by iketheadore** [comment]
A `src_txid` field will be added to all verbose transaction inputs, affected APIs:
-  `/api/v1/transaction`
- `/api/v1/transactions`
- `/api/v1/block`
- `/api/v1/blocks`
- `/api/v1/pendingTxs`
