### ISSUE TITLE
Corrupted files result in ERROR #1 for Linux

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#7]
@SkycnTrnsltns commented on Oct 13

For unknown reasons client.json and peers.json get corrupted.
When the wallet is opened this results in ERROR #1. No log files are written.

content of client.json (full text):
õ}1~�@� ®ô:ç¡�VLm�i

content of peers.json (example text)
�3@*Ã!°6I¨�Ne«�@�ø¿° �

Wallet Version: v0.26
Linux Version:
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"

Error screenshot:
![image](https://user-images.githubusercontent.com/55472625/66824312-3e2da600-ef72-11e9-82fd-7aa4a7c076cf.png)
FIX: Get client.json and peers.json from a fresh .skycoin folder and simple copy them in the folder of the non working wallet.

**Comment by iketheadore** [comment]
Corrupted files in ~/.skycoin/data folder causes this error, the backend should not be crashed, it should be able to recover and backup the corrupted files.

**Comment by SkycnTrnsltns** [comment]
That is the desired behaviour, which does not work. None of the files get recovered. Resulting in the Error #1 permanently.
