### ISSUE TITLE
Find out why the data directory is different between dev and electron builds on windows

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skycoin#89]
@gz-c commented on Aug 24, 2018

Follow this thread for background info:
[#1755 (comment)](https://github.com/skycoin/skycoin/pull/1755#issuecomment-415044618)

**Comment by iketheadore** [comment]
It works fine for me on code of `develop` branch. Both running from `./run-client.sh` and `electron wallet` storing the data in the same directory on windows(Windows 10).

**Comment by iketheadore** [comment]
I will close this issue. Reopen it if this still exists in the future.
